# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development: &defaults
  secret_key_base: fd4e8a95884930c25ebfc3020c53b1f4c128912e33c677f7a5139a110c01b2ef5de41496e446abd4733ad2a3f51404c712acca297d967d651bddfcfd1c1f55aa
  devise:
    :secret_key: 2345678fg67fydg9843uitfgr9udfg8ui3ed89fiyucdv8uifgre80tfhgjv9oaf1324346dtyusfjkdsf8sd976732yhjkkednsc78sgcjhb7wyubhjdf867234ingp
    :pepper: 8d33d1cb747460541109e1bccfc63a82fc9aa251cbe03e3d813985040a88cd37c63c35a6af657f9bb30719f243cee977ff0a431d628657e5e44046e178c3096a
  oauth:
    :facebook:
      :app_id: 337441442986680
      :app_secret: 6750e33a1997602a019e30cdcd79ea13
      :app_permissions: ""
    :vkontakte:
      :app_id: 2427019
      :app_secret: giPYFR7vzBQ0rWf4IIOy
      :app_permissions: ""
    :twitter:
      :secret_key: bvQBEifm3CYy1IN45ZUQeYAJps6fbbi3iYTqhK0uAg
      :consumer_key: IWOVzpgZTRDnjwvB75T9xg
  mailgun:
    :login: 111111111111111111
    :password: 111111111111111111111111
  smtp:
    :login: mail@shikimori.org
    :password: 11111111
  s3:
    connection:
      :server: s3-eu-west-1.amazonaws.com
      :access_key_id: 11111111111111111111
      :secret_access_key: 1111111111111111111111111111111111111111
      :use_ssl: true
      # :persistent: true
    bucket: d.shikimori.org
    max_file_size: 10485760
    acl: public-read
    access_key_id: 11111111111111111111
    secret_access_key: 1111111111111111111111111111111111111111
  gcm:
    :token: 111111111111111111111111111111111111111
  camo:
    :key: abc

test:
  <<: *defaults

production:
 <<: *defaults
